services:
  - type: web
    name: lecture-notes-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # This means the value will be entered manually in the Render dashboard
    plan: free # Start with the free tier
    healthCheckPath: /api/health # Optional: add a health check endpoint
    autoDeploy: true # Auto-deploy on changes to your GitHub repo